version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: gradle-cache-{{ checksum "versions.props" }}-{{ checksum "build.gradle" }}

      - run: ./gradlew --parallel resolveConfigurations

      - save_cache:
          key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - ~/.gradle/wrapper
      - save_cache:
          key: gradle-cache-{{ checksum "versions.props" }}-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle/caches

      - run: ./gradlew --parallel build

      - run:
          command: ./gradlew --parallel copyTestResults
          when: always
      - store_test_results:
          path: /tmp/test-results/

      - persist_to_workspace:
          root: ./
          paths:
            - '*/build/*'
